services:
  proxy:
    container_name: pwc-proxy
    image: nginx:mainline-alpine3.18-slim
    ports:
      - 3500:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - internal

  php:
    container_name: pwc-php
    build: './docker/php'
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - php_sessions:/var/lib/php/sessions
    networks:
      - internal

  php-ws:
    container_name: pwc-php-ws
    build:
      context: './docker/php_openswoole'
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    ports:
      - 127.0.0.1:9501:9501
    volumes:
      - ./ws/:/var/www/
      - ./docker/php_openswoole/php.ini:/usr/local/etc/php/php.ini
      - php_sessions:/var/lib/php/sessions
    networks:
      - internal

volumes:
  php_sessions:
    driver: local  # You can specify a different driver if needed

networks:
  internal:
    driver: bridge